//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COMANDFAST.Layer.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public Producto()
        {
            this.Pedido_Producto = new HashSet<Pedido_Producto>();
        }
    
        public int Id_Producto { get; set; }
        public string Descripcion { get; set; }
        public double Precio { get; set; }
        public string En_Menu { get; set; }
        public int Id_Tipo_Producto { get; set; }
        public int Stock { get; set; }
        public string Activo { get; set; }
    
        public virtual ICollection<Pedido_Producto> Pedido_Producto { get; set; }
        public virtual Tipo_Producto Tipo_Producto { get; set; }
    }
}
