//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COMANDFAST.Layer.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock_Comanfast
    {
        public int Id_Producto { get; set; }
        public Nullable<int> Cantidad { get; set; }
    
        public virtual Producto Producto { get; set; }
    }
}
